/*
 * DebugFrame.java
 *
 * Created on 2008. május 6., 12:03
 */

package smartsettlers;

import smartsettlers.boardlayout.BoardLayout;

/**
 *
 * @author  szityu
 */
public class DebugFrame extends javax.swing.JFrame {

    public BoardLayout boardlayout;
    
    /** Creates new form DebugFrame */
    public DebugFrame() {
        initComponents();

        boardlayout = new BoardLayout(settlersPanel1.getWidth(),settlersPanel1.getHeight());
        settlersPanel1.SetBoardLayout(boardlayout);
        boardlayout.InitBoard();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settlersPanel1 = new smartsettlers.display.SettlersPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settlersPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settlersPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DebugFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private smartsettlers.display.SettlersPanel settlersPanel1;
    // End of variables declaration//GEN-END:variables
    
}
